"""empty message

Revision ID: 24d6686df8e8
Revises: ca83a6d1ef6d
Create Date: 2017-01-18 08:52:01.274762

"""

# revision identifiers, used by Alembic.
revision = '24d6686df8e8'
down_revision = 'ca83a6d1ef6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('total', sa.Numeric(precision=8, scale=2), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimates', 'total')
    ### end Alembic commands ###
