"""empty message

Revision ID: 96b5f618f19b
Revises: 7923d1c19624
Create Date: 2017-01-16 20:34:41.912020

"""

# revision identifiers, used by Alembic.
revision = '96b5f618f19b'
down_revision = '7923d1c19624'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_items', sa.Column('order', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_items', 'order')
    ### end Alembic commands ###
