"""empty message

Revision ID: ca83a6d1ef6d
Revises: 77f4527f948c
Create Date: 2017-01-17 21:19:02.391874

"""

# revision identifiers, used by Alembic.
revision = 'ca83a6d1ef6d'
down_revision = '77f4527f948c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('business_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('fname', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('initial_setup', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('lname', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'lname')
    op.drop_column('user', 'initial_setup')
    op.drop_column('user', 'fname')
    op.drop_column('user', 'business_name')
    ### end Alembic commands ###
